version: '3'
services:
  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "1779:80"

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
    stdin_open: true
  
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    env_file:
      - ./server/dev.env
    volumes:
      - ./server:/app
    depends_on:
      - db
  
  db:
    image: postgres
    restart: always
    env_file:
      - db.env
      
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    env_file:
      - pgadmin.env
      
    ports:
      - "80:80"
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
    depends_on:
      - db