version: '3'
services:
  psql:
    container_name: psql
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=12345

  server:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    env_file:
      - ./server/.env.development
    volumes:
      - ./server:/app/server
    depends_on:
      - psql

  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    env_file:
      - ./client/.env.development
    volumes:
      - ./client:/app/client